import React, { useState, useEffect, useRef } from 'react';
import { Send, Mic, RefreshCw, Copy, Check, MessageSquare, Terminal, BarChart2 } from 'lucide-react';

export default function CopilotPage() {
  const [messages, setMessages] = useState([
    { sender: 'ai', text: "Hello Sarah. I'm connected to the AetherOS Multi-Agent Mesh. Ask me to optimize shipping pathways, forecast regional stockouts, audit custom tax codes, or review carbon metrics." }
  ]);
  const [inputText, setInputText] = useState('');
  const [isTyping, setIsTyping] = useState(false);
  const [copiedIdx, setCopiedIdx] = useState<number | null>(null);
  const [isVoiceActive, setIsVoiceActive] = useState(false);
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const chatEndRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages, isTyping]);

  // Sine Wave Audio Visualizer when mic is active
  useEffect(() => {
    if (!isVoiceActive) return;
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    let animId: number;
    let angle = 0;

    const render = () => {
      ctx.clearRect(0, 0, canvas.width, canvas.height);
      ctx.strokeStyle = '#06b6d4';
      ctx.lineWidth = 2.5;
      ctx.beginPath();

      for (let x = 0; x < canvas.width; x++) {
        // Draw voice wave formula
        const y = canvas.height / 2 + Math.sin(x * 0.05 + angle) * 15 * Math.sin(angle * 0.2);
        if (x === 0) ctx.moveTo(x, y);
        else ctx.lineTo(x, y);
      }

      ctx.stroke();
      angle += 0.15;
      animId = requestAnimationFrame(render);
    };

    render();
    return () => cancelAnimationFrame(animId);
  }, [isVoiceActive]);

  const presetQuestions = [
    { text: "Predict Rotterdam delay risk factors", action: "Identify current maritime delays at Rotterdam Port and list feature importances." },
    { text: "Optimize LA to Singapore path", action: "Reroute Carrier Alpha from Los Angeles to Singapore to bypass storms." },
    { text: "Show SQL for Q2 custom audits", action: "Generate SQL schema query to find all compliance exceptions for Q2." }
  ];

  const handleSend = (text: string) => {
    if (!text.trim()) return;

    // Add user message
    setMessages(prev => [...prev, { sender: 'user', text }]);
    setInputText('');
    setIsTyping(true);

    // Simulate AI response stream
    setTimeout(() => {
      let responseText = "";
      if (text.toLowerCase().includes("sql")) {
        responseText = `Here is the SQL query generated by the Database Agent to audit Q2 custom compliance audit logs:\n\n\`\`\`sql\nSELECT shipment_id, origin_port, destination_port, risk_factor, carbon_tonnes\nFROM shipments\nWHERE departure_date BETWEEN '2026-04-01' AND '2026-06-30'\n  AND status = 'DELAYED'\n  AND compliance_verified = FALSE\nORDER BY risk_factor DESC;\n\`\`\`\n\nThis will extract all unverified delayed cargo shipments, allowing the Compliance Agent to run audits.`;
      } else if (text.toLowerCase().includes("rotterdam")) {
        responseText = `The Rotterdam Port Congestion risk currently stands at **82% (Critical)**.\n\n### Primary Drivers:\n- **Weather front**: Strong Atlantic headwinds slowing approach speeds (42% impact)\n- **Port labor dispute**: Gate processing times extended by 3.4h (30% impact)\n- **Vessel stack**: 14 ships anchored in queue (10% impact)\n\n### Suggested Actions:\n1. Reroute upcoming carriers to **Antwerp Terminal** (+14% shipping fee, saves 42h wait time).\n2. Leverage **inter-modal rail** options through Germany.`;
      } else {
        responseText = `Understood. Analyzing supply chain lanes using the Autonomous Agent Mesh. The Logistics Agent suggests keeping current route parameters as safety stock is at 98.4% capacity. Carbon metrics remain within threshold limits (42.4t offset).`;
      }

      // Stream the message letter by letter
      let currentLength = 0;
      setMessages(prev => [...prev, { sender: 'ai', text: "" }]);
      
      const interval = setInterval(() => {
        currentLength += 3;
        const currentSlice = responseText.slice(0, currentLength);
        setMessages(prev => {
          const updated = [...prev];
          updated[updated.length - 1] = { sender: 'ai', text: currentSlice };
          return updated;
        });

        if (currentLength >= responseText.length) {
          clearInterval(interval);
          setIsTyping(false);
        }
      }, 15);

    }, 1000);
  };

  const copyToClipboard = (text: string, idx: number) => {
    navigator.clipboard.writeText(text);
    setCopiedIdx(idx);
    setTimeout(() => setCopiedIdx(null), 2000);
  };

  return (
    <div className="flex flex-col h-[calc(100vh-40px)] p-6 lg:p-8 space-y-6">
      <div>
        <h2 className="text-3xl font-bold font-sans tracking-tight text-white flex items-center gap-3">
          <span>AI Copilot</span>
          <span className="rounded bg-brand-cyan/20 px-2.5 py-0.5 text-xs text-brand-cyan font-bold tracking-wider uppercase">
            Gemini 1.5 Pro
          </span>
        </h2>
        <p className="text-xs text-brand-muted mt-1">Autonomous Supply Agent mesh conversational interface</p>
      </div>

      {/* Main chat window */}
      <div className="flex-1 glass-panel rounded-3xl p-6 flex flex-col justify-between overflow-hidden relative">
        <div className="absolute inset-0 bg-gradient-to-b from-brand-purple/[0.02] to-transparent z-0 pointer-events-none"></div>

        {/* Scrollable messages container */}
        <div className="relative z-10 flex-1 overflow-y-auto space-y-6 pr-2">
          {messages.map((msg, idx) => (
            <div key={idx} className={`flex ${msg.sender === 'user' ? 'justify-end' : 'justify-start'}`}>
              <div className={`max-w-2xl rounded-2xl p-4 text-sm leading-relaxed ${
                msg.sender === 'user'
                  ? 'bg-brand-purple text-white shadow-lg'
                  : 'bg-white/5 border border-white/5 text-brand-text'
              }`}>
                {/* Parse basic formatting / code blocks */}
                {msg.text.includes("```sql") ? (
                  <div className="space-y-3">
                    <p>{msg.text.split("```sql")[0]}</p>
                    <div className="relative rounded-lg bg-black/40 border border-white/10 p-4 font-mono text-xs overflow-x-auto text-[#06b6d4]">
                      <div className="absolute right-2 top-2">
                        <button
                          onClick={() => copyToClipboard(msg.text.split("```sql")[1].split("```")[0], idx)}
                          className="p-1 rounded text-brand-muted hover:bg-white/5 hover:text-white"
                        >
                          {copiedIdx === idx ? <Check className="h-4 w-4 text-brand-emerald" /> : <Copy className="h-4 w-4" />}
                        </button>
                      </div>
                      <code>{msg.text.split("```sql")[1].split("```")[0]}</code>
                    </div>
                    <p>{msg.text.split("```")[2]}</p>
                  </div>
                ) : (
                  <p className="whitespace-pre-line">{msg.text}</p>
                )}
              </div>
            </div>
          ))}

          {isTyping && (
            <div className="flex justify-start">
              <div className="rounded-2xl p-4 bg-white/5 border border-white/5 text-brand-muted text-xs flex gap-1 items-center">
                <span className="h-1.5 w-1.5 rounded-full bg-brand-cyan animate-bounce" style={{ animationDelay: '0ms' }}></span>
                <span className="h-1.5 w-1.5 rounded-full bg-brand-cyan animate-bounce" style={{ animationDelay: '150ms' }}></span>
                <span className="h-1.5 w-1.5 rounded-full bg-brand-cyan animate-bounce" style={{ animationDelay: '300ms' }}></span>
              </div>
            </div>
          )}
          <div ref={chatEndRef} />
        </div>

        {/* Bouncing Audio waves for voice feed */}
        {isVoiceActive && (
          <div className="absolute bottom-28 left-6 right-6 z-20 flex items-center justify-between border border-brand-cyan/20 bg-[#070712]/90 rounded-2xl p-4">
            <div className="flex items-center gap-3">
              <span className="h-2 w-2 rounded-full bg-brand-cyan animate-ping"></span>
              <span className="text-xs font-bold text-brand-cyan uppercase tracking-wider">Voice Input Tunneled</span>
            </div>
            <canvas ref={canvasRef} className="h-8 w-60" width={240} height={32} />
            <button
              onClick={() => setIsVoiceActive(false)}
              className="text-xs font-bold text-brand-danger hover:underline"
            >
              Stop Voice
            </button>
          </div>
        )}

        {/* Input panel & presets */}
        <div className="relative z-10 border-t border-white/10 pt-4 mt-4 space-y-4">
          {/* Presets */}
          <div className="flex flex-wrap gap-2.5">
            {presetQuestions.map((q, idx) => (
              <button
                key={idx}
                onClick={() => handleSend(q.action)}
                className="flex items-center gap-1.5 rounded-lg border border-white/5 bg-white/5 px-3 py-1.5 text-xs text-brand-muted hover:bg-white/10 hover:text-white transition-all"
              >
                <span>{q.text}</span>
              </button>
            ))}
          </div>

          <div className="flex gap-3">
            <div className="relative flex-1">
              <input
                type="text"
                value={inputText}
                onChange={(e) => setInputText(e.target.value)}
                onKeyDown={(e) => e.key === 'Enter' && handleSend(inputText)}
                placeholder="Ask AetherOS Copilot..."
                className="w-full glass-input pl-4 pr-12 py-3.5 text-sm focus:outline-none"
              />
              <button
                onClick={() => setIsVoiceActive(true)}
                className="absolute right-3 top-3 rounded-lg p-1 text-brand-muted hover:bg-white/5 hover:text-white"
              >
                <Mic className="h-5 w-5" />
              </button>
            </div>
            <button
              onClick={() => handleSend(inputText)}
              className="rounded-xl bg-gradient-to-r from-brand-blue to-brand-purple px-5 py-3.5 text-sm font-semibold hover:opacity-95 transition-opacity"
            >
              <Send className="h-4 w-4" />
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
